import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { ThemeProvider } from "@/components/shadcn/theme/provider";
import Header from "@/components/layout/header";
import "./globals.css";

import Script from "next/script";
import { cn } from "@/lib/utils";
import GoogleApi from "@/components/layout/google-api";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <GoogleApi />
      </head>
      <body
        className={cn(
          "bg-background font-sans antialiased flex flex-col h-screen",
          fontSans.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />

          <main className={"grow max-w-[1440px] self-center"}>{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
